### ISSUE TITLE
Show Telegram username in Minecraft as a mouse hover text

### ISSUE THREAD

**Issue by felixbade** [felixbade/minecraft-telegram-gateway#39]

**Comment by ollpu** [comment]
What should happen when the user has no @-tag?

**Comment by felixbade** [comment]
It could say in the mouseover that the user has no username

**Comment by ollpu** [comment]
Also, have it `suggest_command` when clicked to autofill the message box somehow.

**Comment by felixbade** [comment]
@ollpu Could you create a separate issue about that since it's a different feature?
